---
- name: Install and Start Nginx on EC2
  hosts: webserver
  become: true  # To run tasks as root

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

